# http://southworks.com/blog/2015/07/17/docker-compose-scaling-multi-container-applications/

haproxy:
  image: tutum/haproxy
  links:
   - web
  ports:
   - "80:80"
   
web:
  build: .
  ports:
   - "5000"
  volumes:
   - .:/code
  links:
   - redis
redis:
  image: redis

