# http://southworks.com/blog/2015/07/17/docker-compose-scaling-multi-container-applications/

proxy:
  image: jwilder/nginx-proxy
  volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
  ports:
      - "80:80"
   
web:
  build: .
  ports:
   - "5000"
  volumes:
   - .:/code
  links:
   - redis
  environment:
   - VIRTUAL_HOST=count.dockerhost.example.org
redis:
  image: redis

